[package]
name = "httpfromtcp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["rt", "net" , 'sync', 'macros', 'rt-multi-thread'] }
